name:                autodif
version:             0.1.0.0
github:              "K4DarkBB/autodif"
license:             BSD3
author:              "Unknown"
maintainer:          "kasshi.4259.b.b@gmial.com"
copyright:           "2021 Unknown"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/K4DarkBB/autodif#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  autodif-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autodif

tests:
  autodif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autodif
