[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'guns/xterm-color-table.vim'
[[plugins]]
repo = 'kasshiy/eva01.vim'
[[plugins]]
repo = 'machakann/vim-highlightedyank'
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins]]
repo = 'ChristianChiarulli/nvcode-color-schemes.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
[[plugins]]
repo = 'romgrk/barbar.nvim'
[[plugins]]
repo = 'Xuyuanp/scrollbar.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'tami5/sql.nvim'

[[plugins]]
repo = 'andymass/vim-matchup'
[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = "TSUpdate"
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
[[plugins]]
repo = 'nvim-treesitter/playground'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
[[plugins]]
repo = 'windwp/nvim-autopairs'
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
[[plugins]]
repo = 'onsails/lspkind-nvim'
[[plugins]]
repo = 'folke/trouble.nvim' 
[[plugins]]
repo = 'b3nj5m1n/kommentary'
hook_add = '''
lua require('kommentary.config').use_extended_mappings()
'''


[[plugins]]
repo = 'hrsh7th/nvim-cmp' 
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'ray-x/cmp-treesitter' 
[[plugins]]
repo = 'rsh7th/cmp-calc' 
[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
