[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'guns/xterm-color-table.vim'
[[plugins]]
repo = 'kasshiy/eva01.vim'
[[plugins]]
repo = 'machakann/vim-highlightedyank'
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins]]
repo = 'ChristianChiarulli/nvcode-color-schemes.vim'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
[[plugins]]
repo = 'romgrk/barbar.nvim'

[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'markonm/traces.vim'
[[plugins]]
repo = 'phaazon/hop.nvim'

[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tpope/vim-unimpaired'
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
[[plugins]]
repo = 'kdheepak/lazygit.nvim'

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = "call fzf#install()"
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
hook_post_update = "make"
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope-hop.nvim'
hook_add = '''
lua require'telescope'.load_extension'hop'
'''
[[plugins]]
repo = 'nvim-telescope/telescope-github.nvim'
hook_add = '''
lua require'telescope'.load_extension'gh'
'''
[[plugins]]
repo = 'nvim-telescope/telescope-ghq.nvim'
hook_add = '''
lua require'telescope'.load_extension'ghq'
'''
[[plugins]]
repo = 'tami5/sql.nvim'
[[plugins]]
repo = 'glepnir/dashboard-nvim'

[[plugins]]
repo = 'andymass/vim-matchup'
[[plugins]]
repo = 'anott03/nvim-lspinstall'
hook_add = '''
local function setup_servers()
  require'lspinstall'.setup()
  local servers = require'lspinstall'.installed_servers()
  for _, server in pairs(servers) do
    require'lspconfig'[server].setup{}
  end
end

setup_servers()

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim
require'lspinstall'.post_install_hook = function ()
  setup_servers() -- reload installed servers
  vim.cmd("bufdo e") -- this triggers the FileType autocmd that starts the server
end
'''
[[plugins]]
repo = 'kasshiy/nvim-lspconfig'
[[plugins]]
repo = 'nvim-lua/completion-nvim'
hook_add = 'let g:completion_enable_auto_paren = 1'
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = "TSUpdate"
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
[[plugins]]
repo = 'nvim-treesitter/playground'
[[plugins]]
repo = 'nvim-treesitter/completion-treesitter'
[[plugins]]
repo = 'nvim-treesitter-refactor'
[[plugins]]
repo = 'windwp/nvim-autopairs'
[[plugins]]
repo = 'nvim-lua/lsp-status.nvim'
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
[[plugins]]
repo = 'onsails/lspkind-nvim'
[[plugins]]
repo = 'b3nj5m1n/kommentary'
hook_add = '''
lua require('kommentary.config').use_extended_mappings()
'''

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
[[plugins]]
repo = 'purescript-contrib/purescript-vim' 
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'let g:rustfmt_autosave = 1'
[[plugins]]
repo = 'simrat39/rust-tools.nvim' 
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_post_update = 'call mkdp#util#install()'
[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'vhdirk/vim-cmake'
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
[[plugins]]
repo = 'ronakg/quickr-preview.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'junegunn/goyo.vim'
[[plugins]]
repo = 'junegunn/limelight.vim'

[[plugins]]
repo = 'deris/vim-duzzle'
